import type { AdTemplate } from '@/types';

export const AD_TEMPLATES: AdTemplate[] = [
  // ─── CUSTOMER ADS ────────────────────────────────────────────────────────────
  {
    id: 'c1',
    category: 'customer',
    title: 'Earn Rewards Every Visit',
    headline: 'Every visit\nearns you more.',
    subheadline: 'Stamps, rewards & perks — all in one app.',
    caption: 'Never lose a paper stamp again. ClientIn keeps all your loyalty cards in one place. ☕✂️💅',
    cta: 'Download Free',
    screenshot: '/3.png',
    layout: 'screenshot-right',
    accentColor: '#D97706',
    darkMode: true,
    badge: 'FOR CUSTOMERS',
  },
  {
    id: 'c2',
    category: 'customer',
    title: 'Discover Local Spots',
    headline: 'Find the best\nlocal shops\nnear you.',
    subheadline: 'Top-rated salons, cafés & barbers — with rewards.',
    caption: 'Discover hidden gems in your city and get rewarded every time you come back. 📍',
    cta: 'Explore Now',
    screenshot: '/2.png',
    layout: 'screenshot-left',
    accentColor: '#D97706',
    darkMode: false,
    badge: 'DISCOVER',
  },
  {
    id: 'c3',
    category: 'customer',
    title: 'Your Wallet, Your Rewards',
    headline: 'All your\nloyalty cards.\nOne wallet.',
    subheadline: '3 cards. 85 visits. 6 rewards ready to use.',
    caption: 'From your barber to your fave café — all your stamps live here. Never start from scratch again.',
    cta: 'Get the App',
    screenshot: '/3.png',
    layout: 'screenshot-bg',
    accentColor: '#D97706',
    darkMode: true,
    badge: 'MY WALLET',
  },
  {
    id: 'c4',
    category: 'customer',
    title: 'One App, Every Local Favourite',
    headline: 'Loyalty that\nactually fits\nyour life.',
    subheadline: 'Barbershops, cafés, salons, restaurants — all on ClientIn.',
    caption: 'Stop carrying paper cards. One tap to earn, one tap to redeem. This is how loyalty should work.',
    cta: 'Download ClientIn',
    screenshot: '/1.png',
    layout: 'screenshot-right',
    accentColor: '#D97706',
    darkMode: true,
  },

  // ─── BUSINESS OWNER ADS ──────────────────────────────────────────────────────
  {
    id: 'b1',
    category: 'business',
    title: '75% Repeat Rate',
    headline: '75% of your\ncustomers\ncame back.',
    subheadline: '186 returning customers in 90 days.',
    caption: 'That\'s not luck. That\'s ClientIn. See exactly who\'s returning, who\'s at risk, and who\'s ready to redeem.',
    cta: 'Grow My Business',
    screenshot: '/4.png',
    layout: 'screenshot-right',
    accentColor: '#D97706',
    darkMode: true,
    badge: 'FOR BUSINESSES',
  },
  {
    id: 'b2',
    category: 'business',
    title: 'Know Your Customers',
    headline: 'Real insight.\nReal growth.',
    subheadline: '247 customers. 18 check-ins today. 12 active rewards.',
    caption: 'Your dashboard shows you everything — who visited, who hasn\'t, and who\'s close to a reward.',
    cta: 'See the Dashboard',
    screenshot: '/5.png',
    layout: 'screenshot-left',
    accentColor: '#D97706',
    darkMode: false,
    badge: 'INSIGHTS',
  },
  {
    id: 'b3',
    category: 'business',
    title: 'Customer Insights at a Glance',
    headline: 'Stop guessing.\nStart knowing.',
    subheadline: '+9.9% visits this month. 12 customers need attention.',
    caption: 'ClientIn tells you who\'s slipping away before it\'s too late. Act on data, not gut feeling.',
    cta: 'Try ClientIn',
    screenshot: '/5.png',
    layout: 'screenshot-bg',
    accentColor: '#D97706',
    darkMode: true,
    badge: 'ANALYTICS',
  },
  {
    id: 'b4',
    category: 'business',
    title: 'Build Loyalty In Minutes',
    headline: 'Your loyalty\nprogram.\nLive today.',
    subheadline: 'No hardware. No setup fees. No tech skills needed.',
    caption: 'Create a loyalty program for your business in minutes. Your customers download the app — and you keep them coming back.',
    cta: 'Get Started Free',
    screenshot: '/4.png',
    layout: 'screenshot-right',
    accentColor: '#D97706',
    darkMode: true,
    badge: 'FOR OWNERS',
  },

  // ─── APP LAUNCH ADS ──────────────────────────────────────────────────────────
  {
    id: 'l1',
    category: 'launch',
    title: 'ClientIn Is Here',
    headline: 'Loyalty,\nreinvented\nfor locals.',
    subheadline: 'The app that turns first-time customers into regulars.',
    caption: 'ClientIn is now live. Download free and start earning — or start growing. 🎉',
    cta: 'Download Now',
    screenshot: '/1.png',
    layout: 'screenshot-center',
    accentColor: '#D97706',
    darkMode: true,
    badge: '🚀 NOW LIVE',
  },
  {
    id: 'l2',
    category: 'launch',
    title: 'For Customers & Businesses',
    headline: 'One app.\nTwo sides.\nEndless loyalty.',
    subheadline: 'Are you a customer or a business owner?',
    caption: 'Whether you\'re earning stamps or building a customer base — ClientIn is built for you.',
    cta: 'Get ClientIn',
    screenshot: '/1.png',
    layout: 'screenshot-right',
    accentColor: '#D97706',
    darkMode: true,
    badge: 'INTRODUCING',
  },
  {
    id: 'l3',
    category: 'launch',
    title: 'Turn First-Timers Into Regulars',
    headline: 'First visit.\nNot the last.',
    subheadline: 'ClientIn helps local businesses build real loyalty.',
    caption: 'The loyalty platform built for barbershops, cafés, salons and restaurants. Now available on iOS.',
    cta: 'Download on App Store',
    screenshot: '/2.png',
    layout: 'screenshot-left',
    accentColor: '#D97706',
    darkMode: false,
    badge: 'APP LAUNCH',
  },
  {
    id: 'l4',
    category: 'launch',
    title: 'Available Now on iOS',
    headline: 'Download\nClientIn\ntoday.',
    subheadline: 'Free for customers. Simple setup for businesses.',
    caption: 'Join hundreds of local businesses already building loyalty with ClientIn. Free to download. 📲',
    cta: 'Download Free on iOS',
    screenshot: '/3.png',
    layout: 'screenshot-bg',
    accentColor: '#D97706',
    darkMode: true,
    badge: '📲 iOS',
  },
];

export const CATEGORIES = [
  { id: 'customer' as const, label: 'Customer Ads', emoji: '👤', desc: 'Speak to customers — rewards, discovery, wallet' },
  { id: 'business' as const, label: 'Business Ads', emoji: '💼', desc: 'Speak to owners — retention, insights, setup' },
  { id: 'launch' as const, label: 'App Launch', emoji: '🚀', desc: 'Announce ClientIn — download CTAs, brand story' },
];
